likert_scale = {
    "bfi1": "Is outgoing, sociable:",
    "bfi2": "Is compassionate, has a soft heart:",
    "bfi3": "Tends to be disorganized:",
    "bfi4": "Is relaxed, handles stress well:",
    "bfi5": "Has few artistic interests:",
    "bfi6": "Has an assertive personality:",
    "bfi7": "Is respectful, treats others with respect:",
    "bfi8": "Tends to be lazy:",
    "bfi9": "Stays optimistic after experiencing a setback:",
    "bfi10": "Is curious about many different things:",
    "bfi11": "Rarely feels excited or eager:",
    "bfi12": "Tends to find fault with others:",
    "bfi13": "Is dependable, steady:",
    "bfi14": "Is moody, has up and down mood swings:",
    "bfi15": "Is inventive, finds clever ways to do things:",
    "bfi16": "Tends to be quiet:",
    "bfi17": "Feels little sympathy for others:",
    "bfi18": "Is systematic, likes to keep things in order:",
    "bfi19": "Can be tense:",
    "bfi20": "Is fascinated by art, music, or literature:",
    "bfi21": "Is dominant, acts as a leader:",
    "bfi22": "Starts arguments with others:",
    "bfi23": "Has difficulty getting started on tasks:",
    "bfi24": "Feels secure, comfortable with self:",
    "bfi25": "Avoids intellectual, philosophical discussions:",
    "bfi26": "Is less active than other people:",
    "bfi27": "Has a forgiving nature:",
    "bfi28": "Can be somewhat careless:",
    "bfi29": "Is emotionally stable, not easily upset:",
    "bfi30": "Has little creativity:",
    "bfi31": "Is sometimes shy, introverted:",
    "bfi32": "Is helpful and unselfish with others:",
    "bfi33": "Keeps things neat and tidy:",
    "bfi34": "Worries a lot:",
    "bfi35": "Values art and beauty:",
    "bfi36": "Finds it hard to influence people:",
    "bfi37": "Is sometimes rude to others:",
    "bfi38": "Is efficient, gets things done:",
    "bfi39": "Often feels sad:",
    "bfi40": "Is complex, a deep thinker:",
    "bfi41": "Is full of energy:",
    "bfi42": "Is suspicious of others' intentions:",
    "bfi43": "Is reliable, can always be counted on:",
    "bfi44": "Keeps their emotions under control:",
    "bfi45": "Has difficulty imagining things:",
    "bfi46": "Is talkative:",
    "bfi47": "Can be cold and uncaring:",
    "bfi48": "Leaves a mess, doesn't clean up:",
    "bfi49": "Rarely feels anxious or afraid:",
    "bfi50": "Thinks poetry and plays are boring:",
    "bfi51": "Prefers to have others take charge:",
    "bfi52": "Is polite, courteous toward others:",
    "bfi53": "Is persistent, works until the task is finished:",
    "bfi54": "Tends to feel depressed, blue:",
    "bfi55": "Has little interest in abstract ideas:",
    "bfi56": "Shows a lot of enthusiasm:",
    "bfi57": "Assumes the best about people:",
    "bfi58": "Sometimes behaves irresponsibly:",
    "bfi59": "Is temperamental, gets emotional easily:",
    "bfi60": "Is original, comes up with new ideas:"
}